name: communitary_service_app
description: Project to track childrens alimentation.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.11
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_fonts: ^6.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  lottie: ^3.1.2
  open_filex: ^4.5.0
  path_provider: ^2.1.4
  pdf: ^3.11.1
  shared_preferences: ^2.2.3
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.9
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  rename_app: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - .env
    - assets/lotties/
    - assets/icon/

flutter_icons:
  android: "android"
  ios: "ios"
  image_path_android: "assets/icon/playstore.png"
  image_path_ios: "assets/icon/appstore.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"

analyzer:
  exclude:
    - .env
