name: communitary_service_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  formz: ^0.7.0
  freezed: ^2.5.2
  get_it: ^7.6.7
  go_router: ^14.0.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  rename_app: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo/

flutter_icons:
  android: "android"
  ios: "ios"
  image_path_android: "assets/icon/playstore.png"
  image_path_ios: "assets/icon/appstore.png"
  remove_alpha_ios: true
