name: Flutter CI
run-name: "Flutter CI executed by ${{github.actor}} 🛸"

on:
  - push

jobs:
  flutter_ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      id: flutter-action
      with:
        channel: stable
        flutter-version: '3.16.9' # Specify the Flutter version
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Run lint checks
      run: flutter analyze

    # TODO: Agregar ejecución de tests 

